### ISSUE TITLE
Fbx not importing in blender

### ISSUE THREAD

**Issue by nigelmerle** [Varneon/UnityFBX-To-Blender-Importer#1]
Hello I am using blender 3.01 and unity 2020 3.26f1 , i followed your tutorial but the fbx (ascii) doesnt show up in blender.

can you help

**Comment by nigelmerle** [comment]
Hello I just succeeded to import an fbx binary file from unity to blender, however the exporter export only one animation, I have many actions in my fbx and only the first one is exported to blender, is it possible to bypass this limitation ?

**Comment by Varneon** [comment]
Hi!

Are you able to import the FBX model manually into Blender without the usage of additional plugins with all of the animations 
still on it?

-Varneon

**Comment by nigelmerle** [comment]
Now i can, i had to change a bunch of settings in blender fbx importer scripts located in both unity and blender folders....they were not configured correctlyOn Feb 3, 2022 18:19, Varneon ***@***.***> wrote:
Hi!
Are you able to import the FBX model manually into Blender with all of the animations on it?
-Varneon

**Comment by nigelmerle** [comment]
Also i have bought a plugin called better fbx on blender market, im using this instead of blender internal fbx which is a mess to useOn Feb 3, 2022 18:19, Varneon ***@***.***> wrote:
Hi!
Are you able to import the FBX model manually into Blender with all of the animations on it?
-Varneon

**Comment by Varneon** [comment]
I will be closing this issue since the original problem stated in the original message has been resolved (UnityFBX-To-Blender-Importer uses Blender's built-in FBX importer and doesn't support ASCII FBX)

UnityFBX-To-Blender-Importer doesn't support importing FBX models using 3rd-party Blender addons, but if you wish for such feature to be added, feel free to create a new issue related to it or create a pull request if you have managed to create a suitable solution for it.

-Varneon

**Comment by nigelmerle** [comment]
Well the issue isnt resolved in blender itself because i am using an
external addon better fbx to import and export my characters.
The internal importer totally distort all the characters it is totally
useless and only binary format can be imported with blender internal fbx

**Comment by nigelmerle** [comment]
I have updated my unity as well, it is working, so yeah no issuesThank u for your helpOn Feb 3, 2022 19:37, Varneon ***@***.***> wrote:
Closed #1.
